### ISSUE TITLE
update dependency support dart 3 and flutter >= 3.7

### ISSUE THREAD

**Issue by kait-it** [TOPdesk/dart-junitreport#45]
Our application depends on the intl 0.18.1 plugin, as Flutter SDK > 3.7 forces this.

Error message:

Because junitreport 2.0.2 depends on intl ^0.17.0 and no versions of junitreport match >2.0.2 <3.0.0, junitreport ^2.0.2 requires intl ^0.17.0.

Solution: 
update extension to s intl ^0.18.1

**Comment by apptodrive** [comment]
`Because junitreport >=2.0.0 depends on xml ^5.3.1 and flutter_svg 1.1.6 depends on xml ^6.0.1, junitreport >=2.0.0 is incompatible with flutter_svg 1.1.6.
So, because ... depends on both flutter_svg 1.1.6 and junitreport 2.0.0, version solving failed.
`

**Comment by chrystoffer** [comment]
It is possible to add dependency_overrides so that it can be used. In my case, there was a conflict with the XML.
Just add it to the pubspec.yaml:

dependency_overrides:
  xml: ^6.5.0

**Comment by waffiqaziz** [comment]
If you're looking for a working alternative with Flutter `3.32.xx`, I've created a fork of this package with updated compatibility:

```yml
dependencies:
  flutter_junitreport:
    git:
      url: https://github.com/waffiqaziz/flutter-junitreport.git
      ref: main

executables:
  tojunit:
```

You can use it like this:
```shell
flutter pub get
flutter test --coverage --reporter json > test.jsonl
dart pub global activate --source git https://github.com/waffiqaziz/flutter-junitreport.git
dart pub global run flutter_junitreport:tojunit --input test.jsonl --output TEST-report.xml
```
